# Generated by Django 4.2.16 on 2026-05-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_normalize_user_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits_remaining',
            field=models.IntegerField(default=0, verbose_name='Envíos disponibles'),
        ),
    ]
