# Generated by Django 4.2.16 on 2026-05-03 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_area_location_company_area_fk_company_location_fk'),
        ('accounts', '0006_alter_user_credits_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_filter_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.area'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_filter_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.location'),
        ),
    ]
