# Generated by Django 4.2.16 on 2026-05-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_area_fk_remove_company_location_fk_and_more'),
        ('accounts', '0007_user_area_filter_fk_user_location_filter_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_filter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_filter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='area_filter_fk',
            new_name='area_filter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='location_filter_fk',
            new_name='location_filter',
        ),
    ]
