# Generated by Django 4.2.16 on 2026-05-03 22:05

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_area_filter_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(storage=apps.accounts.models._private_storage, upload_to='cvs/'),
        ),
    ]
