# Generated by Django 4.2.16 on 2026-05-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companyimportbatch_upload_uuid_and_original_filename'),
        ('accounts', '0009_alter_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_filters',
            field=models.ManyToManyField(blank=True, related_name='users_m2m', to='companies.area'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_filters',
            field=models.ManyToManyField(blank=True, related_name='users_m2m', to='companies.location'),
        ),
    ]
