# Generated by Django 4.2.16 on 2026-05-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_migrate_user_filters_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_filter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_filter',
        ),
    ]
