# Generated by Django 4.2.16 on 2026-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_old_user_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_purchased_credits',
            field=models.IntegerField(default=0, verbose_name='Total de envíos comprados'),
        ),
    ]
