# Generated by Django 4.2.16 on 2026-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_populate_total_purchased_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campaign_pause_reason',
            field=models.CharField(blank=True, max_length=20, verbose_name='Razón de pausa de campaña'),
        ),
    ]
