# Generated by Django 4.2.16 on 2026-05-27 03:28

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_area_name_alter_blacklist_added_at_and_more'),
        ('accounts', '0015_user_campaign_pause_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(storage=apps.accounts.models._private_storage, upload_to='cvs/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.cv', verbose_name='CV activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area_filters',
            field=models.ManyToManyField(blank=True, related_name='users_m2m', to='companies.area', verbose_name='Filtros de sector'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_campaign_active',
            field=models.BooleanField(default=False, verbose_name='Campaña activa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_filters',
            field=models.ManyToManyField(blank=True, related_name='users_m2m', to='companies.location', verbose_name='Filtros de localidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ID de cliente Stripe'),
        ),
    ]
