# Generated by Django 4.2.16 on 2026-05-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_cv_created_at_alter_cv_file_alter_cv_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_low_credits_warning_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última alerta de créditos bajos'),
        ),
    ]
