# Generated by Django 5.2.15 on 2026-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_last_low_credits_warning_at'),
        ('companies', '0014_subarea_company_sub_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_area_filters',
            field=models.ManyToManyField(blank=True, related_name='users_m2m', to='companies.subarea', verbose_name='Filtros de subactividad'),
        ),
    ]
