# Generated by Django 4.2.16 on 2026-05-03 02:36

from django.db import migrations

def populate_taxonomy(apps, schema_editor):
    Area = apps.get_model('companies', 'Area')
    Location = apps.get_model('companies', 'Location')
    Company = apps.get_model('companies', 'Company')
    User = apps.get_model('accounts', 'User')

    # Collect all unique areas and locations from Company and User
    areas = set(Company.objects.values_list('area', flat=True))
    areas.update(User.objects.values_list('area_filter', flat=True))
    
    locations = set(Company.objects.values_list('location', flat=True))
    locations.update(User.objects.values_list('location_filter', flat=True))

    # Remove empty strings
    areas = {a for a in areas if a}
    locations = {l for l in locations if l}

    # Create Area and Location objects
    area_objs = {name: Area.objects.get_or_create(name=name)[0] for name in areas}
    location_objs = {name: Location.objects.get_or_create(name=name)[0] for name in locations}

    # Link Companies
    for company in Company.objects.all():
        if company.area and company.area in area_objs:
            company.area_fk = area_objs[company.area]
        if company.location and company.location in location_objs:
            company.location_fk = location_objs[company.location]
        company.save(update_fields=['area_fk', 'location_fk'])

    # Link Users
    for user in User.objects.all():
        if user.area_filter and user.area_filter in area_objs:
            user.area_filter_fk = area_objs[user.area_filter]
        if user.location_filter and user.location_filter in location_objs:
            user.location_filter_fk = location_objs[user.location_filter]
        user.save(update_fields=['area_filter_fk', 'location_filter_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_area_location_company_area_fk_company_location_fk'),
        ('accounts', '0007_user_area_filter_fk_user_location_filter_fk'),
    ]

    operations = [
        migrations.RunPython(populate_taxonomy, reverse_code=migrations.RunPython.noop),
    ]
