# Generated by Django 4.2.16 on 2026-05-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_populate_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='area',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='area_fk',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='location_fk',
            new_name='location',
        ),
    ]
