# Generated by Django 4.2.16 on 2026-05-06 23:11

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyimportbatch_blacklisted_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimportbatch',
            name='file',
            field=models.FileField(blank=True, storage=apps.companies.models._imports_storage, upload_to='companies/%Y/%m/%d/'),
        ),
    ]
