# Generated by Django 4.2.16 on 2026-05-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_companyimportbatch_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimportbatch',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyimportbatch',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
