# Generated by Django 4.2.16 on 2026-05-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_companyimportbatch_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimportbatch',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyimportbatch',
            name='upload_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
