# Generated by Django 4.2.16 on 2026-05-27 03:28

import apps.companies.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companyimportbatch_upload_uuid_and_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Añadido el'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.CharField(default='unsubscribe', max_length=100, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.area', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='community',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comunidad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último envío recibido'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.location', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='blacklisted_skipped',
            field=models.IntegerField(default=0, verbose_name='Omitidas (lista negra)'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='created_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Empresas creadas'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='error_log',
            field=models.JSONField(blank=True, default=list, verbose_name='Registro de errores'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='file',
            field=models.FileField(blank=True, storage=apps.companies.models._imports_storage, upload_to='companies/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de archivo original'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Filas procesadas'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='total_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de filas'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizada el'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Empresas actualizadas'),
        ),
        migrations.AlterField(
            model_name='companyimportbatch',
            name='upload_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID de subida'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
