# Generated by Django 5.2.15 on 2026-06-07 12:19

import apps.companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_area_name_alter_blacklist_added_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Subactividad',
                'verbose_name_plural': 'Subactividades',
                'ordering': ['name'],
            },
            bases=(apps.companies.models.LowercaseFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.subarea', verbose_name='Subactividad'),
        ),
    ]
