# Generated by Django 4.2.16 on 2026-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_emails_to_sent_folder', models.BooleanField(default=False, help_text="Si está desactivado, los correos enviados no se guardarán en la carpeta 'Enviados' (Sent).")),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
    ]
