# Generated by Django 4.2.16 on 2026-05-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditpackage',
            options={'ordering': ['order', 'price_eur'], 'verbose_name': 'Paquete de Envíos', 'verbose_name_plural': 'Paquetes de Envíos'},
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='credits',
            field=models.IntegerField(verbose_name='Envíos'),
        ),
    ]
