# Generated by Django 4.2.16 on 2026-05-27 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_creditpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='amount_eur',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Importe (€)'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado el'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='credits_granted',
            field=models.IntegerField(default=0, verbose_name='Envíos otorgados'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.creditpackage', verbose_name='Paquete'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=300, verbose_name='Payment intent Stripe'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_session_id',
            field=models.CharField(max_length=300, unique=True, verbose_name='ID de sesión Stripe'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
