# Generated by Django 4.2.16 on 2026-04-24 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre interno para identificar la plantilla', max_length=100)),
                ('subject', models.CharField(help_text='Asunto del email. Placeholders: {company_name}', max_length=300)),
                ('body_html', models.TextField(help_text='Cuerpo HTML del email. Placeholders: {company_name}, {cv_url}, {unsubscribe_url}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_send_interval_minutes', models.IntegerField(default=5, help_text='Minutos entre envíos por usuario (Slow-Drip)')),
                ('company_cooldown_hours', models.IntegerField(default=12, help_text='Horas que deben pasar antes de que una empresa reciba otro CV')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_download_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('unsubscribe_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('company_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_logs', to='companies.company')),
                ('email_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Envío',
                'verbose_name_plural': 'Registros de Envíos',
                'ordering': ['-sent_at'],
            },
        ),
    ]
