# Generated by Django 4.2.16 on 2026-04-28 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailinglog_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(help_text='Cuerpo HTML del email. Placeholders: {company_name}, {cv_url}, {unsubscribe_url}. Máximo 50,000 caracteres.', validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
    ]
