# Generated by Django 4.2.16 on 2026-05-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_emailtemplate_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_emails_per_day_per_user',
            field=models.IntegerField(default=50, help_text='Límite máximo de correos por usuario en 24 horas'),
        ),
    ]
