# Generated by Django 4.2 on 2026-05-14 05:22

import re
from django.db import migrations

def remove_cv_url_from_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("mailing", "EmailTemplate")
    for template in EmailTemplate.objects.all():
        updated = False
        
        # Replace the HTML links containing {cv_url} with a note that the CV is attached.
        # We look for <a ...>{cv_url}...</a> and standard phrases preceding them.
        
        # Case 1: Directo
        body = template.body_html
        body = re.sub(
            r'<p>Adjunto el enlace a mi currículum para su revisión:</p>\s*<p><a href="\{cv_url\}"[^>]*>.*?</a></p>',
            '<p>Adjunto mi currículum en formato PDF para su revisión.</p>',
            body,
            flags=re.DOTALL
        )
        
        # Case 2: Breve
        body = re.sub(
            r'<p>Les dejo por aquí mi CV por si tuvieran alguna oportunidad abierta o quisieran\s*tenerme en cuenta para el futuro:</p>\s*<p>➡ <a href="\{cv_url\}">.*?</a></p>',
            '<p>Adjunto mi CV por si tuvieran alguna oportunidad abierta o quisieran tenerme en cuenta para el futuro.</p>',
            body,
            flags=re.DOTALL
        )
        
        # Case 3: Motivacional
        body = re.sub(
            r'<p>Aquí está mi CV:</p>\s*<p><a href="\{cv_url\}"[^>]*>.*?</a></p>',
            '<p>Encuentren mi CV adjunto a este correo.</p>',
            body,
            flags=re.DOTALL
        )
        
        # Generic fallback for any other custom templates containing {cv_url}
        if '{cv_url}' in body:
            body = re.sub(r'<a[^>]*href=[\'"]?\{cv_url\}[\'"]?[^>]*>.*?</a>', '<strong>(CV adjunto a este correo)</strong>', body)
            body = body.replace('{cv_url}', '')
            
        if body != template.body_html:
            template.body_html = body
            template.save(update_fields=["body_html"])


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_emailtemplate_body_html'),
    ]

    operations = [
        migrations.RunPython(remove_cv_url_from_templates, reverse_code=migrations.RunPython.noop),
    ]
