# Generated by Django 4.2.16 on 2026-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_auto_20260514_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='hidden_credit_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador oculto para envíos extra (ej: 1.10 = 10% extra)', max_digits=4),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='initial_free_credits',
            field=models.IntegerField(default=5, help_text='Envíos gratuitos otorgados al registrarse'),
        ),
    ]
