# Generated by Django 4.2.16 on 2026-05-14 08:15

from django.db import migrations
from django.db.models.functions import Lower


def normalize_mailing_log_emails(apps, schema_editor):
    MailingLog = apps.get_model("mailing", "MailingLog")
    MailingLog.objects.filter(company_email_snapshot__isnull=False).update(
        company_email_snapshot=Lower("company_email_snapshot")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_systemsettings_hidden_credit_multiplier_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_mailing_log_emails, migrations.RunPython.noop),
    ]
