# Generated by Django 4.2.16 on 2026-05-27 03:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_alter_cv_created_at_alter_cv_file_alter_cv_name_and_more'),
        ('companies', '0013_alter_area_name_alter_blacklist_added_at_and_more'),
        ('mailing', '0012_add_displayed_sends_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(help_text='Cuerpo HTML del email. Placeholders: {company_name}, {unsubscribe_url}. Máximo 50,000 caracteres.', validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Cuerpo HTML'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Nombre interno para identificar la plantilla', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='Asunto del email. Placeholders: {company_name}', max_length=300, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_logs', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='company_email_snapshot',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la empresa'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_logs', to='accounts.cv', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='cv_download_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Token de descarga del CV'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.emailtemplate', verbose_name='Plantilla de email'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de error'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado el'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], default='sent', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='unsubscribe_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Token de baja'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='company_cooldown_hours',
            field=models.IntegerField(default=12, help_text='Horas que deben pasar antes de que una empresa reciba otro CV', verbose_name='Enfriamiento por empresa (horas)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='global_send_interval_minutes',
            field=models.IntegerField(default=5, help_text='Minutos entre envíos por usuario (Slow-Drip)', verbose_name='Intervalo de envío (minutos)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='hidden_credit_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador oculto para envíos extra (ej: 1.10 = 10% extra)', max_digits=4, verbose_name='Multiplicador oculto de envíos'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='initial_free_credits',
            field=models.IntegerField(default=5, help_text='Envíos gratuitos otorgados al registrarse', verbose_name='Envíos gratuitos iniciales'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_emails_per_day_per_user',
            field=models.IntegerField(default=50, help_text='Límite máximo de correos por usuario en 24 horas', verbose_name='Máximo de envíos por usuario al día'),
        ),
    ]
