# Generated by Django 4.2.16 on 2026-05-28 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_emailtemplate_body_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_brand_color',
            field=models.CharField(default='#007BFF', help_text='Código hexadecimal del color de marca (ej: #007BFF).', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Debe ser un color hexadecimal válido (ej: #007BFF).')], verbose_name='Color de marca del email'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_footer_text',
            field=models.TextField(default='© 2026 FastJob. Todos los derechos reservados.', help_text='Texto que aparecerá en el pie de página de los correos.', verbose_name='Texto del pie de página'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_logo_url',
            field=models.URLField(default='https://raw.githubusercontent.com/daridev/fastjob/main/static/images/fastjob-logo.png', help_text='URL de la imagen del logo que aparecerá en los correos.', verbose_name='URL del logo de email'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='low_credits_threshold',
            field=models.IntegerField(default=0, help_text='Número de créditos bajo el cual se enviará una alerta.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Umbral de alerta de créditos bajos'),
        ),
    ]
