# Generated by Django 4.2.16 on 2026-05-28 21:40

from django.db import migrations, models


def update_logo_url(apps, schema_editor):
    SystemSettings = apps.get_model('mailing', 'SystemSettings')
    old_url = "https://raw.githubusercontent.com/daridev/fastjob/main/static/images/fastjob-logo.png"
    new_url = "https://raw.githubusercontent.com/darideveloper/fastjob/refs/heads/main/static/images/fastjob-logo.png"
    SystemSettings.objects.filter(email_logo_url=old_url).update(email_logo_url=new_url)

class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_systemsettings_email_brand_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='email_logo_url',
            field=models.URLField(default='https://raw.githubusercontent.com/darideveloper/fastjob/refs/heads/main/static/images/fastjob-logo.png', help_text='URL de la imagen del logo que aparecerá en los correos.', verbose_name='URL del logo en emails'),
        ),
        migrations.RunPython(update_logo_url, reverse_code=migrations.RunPython.noop),
    ]
