# Generated by Django 4.2.16 on 2026-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_update_logo_url_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='save_emails_to_sent_folder',
        ),
    ]
