# Generated by Django 5.2.15 on 2026-06-08 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0016_remove_systemsettings_save_emails_to_sent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_sending_end_time',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Hora local a la que finaliza el envío diario de correos.', verbose_name='Hora de fin de envío'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_sending_start_time',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Hora local a la que se inicia el envío diario de correos.', verbose_name='Hora de inicio de envío'),
        ),
    ]
