# Generated by Django 5.2.15 on 2026-06-14 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_systemsettings_email_sending_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='email_sending_end_time',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Hora límite hasta la cual se pueden enviar correos (Slow-Drip).', verbose_name='Hora de fin de envío'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='email_sending_start_time',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Hora a partir de la cual se pueden enviar correos (Slow-Drip).', verbose_name='Hora de inicio de envío'),
        ),
    ]
